name: CI Meson

on:
  
  workflow_dispatch:

  push:
    paths:
      - 'src/**.h'
      - 'src/**.cpp'
      - 'tests/**.*'

  pull_request:
    paths:    
      - 'src/**.h'
      - 'src/**.cpp'
      - 'tests/**.*'

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-2022]
        meson_version: ["1.5.0", "1.6.0",]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install meson==${{ matrix.meson_version }} ninja gcovr clang-format clang-tidy

      - name: Configure Project
        run: meson setup builddir/
        env:
          CC: gcc

      - name: Compile Debug Version
        run: meson compile -C builddir/ -v cDebug tDebug gDebug

      - name: Run Tests
        run: meson test -C builddir/ -v --suite t_timer
           
      - name: Generating Coverage Report 
        if: matrix.os !='windows-*'
        run: ninja coverage-html -C builddir/

      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}_MesonLogsV${{ matrix.meson_version }}
          path: |
            ./builddir/meson-logs/**.*
          if-no-files-found: error # optional, default is warn  
          retention-days: 7 # optional
          include-hidden-files: false # optional, default is false
  
  Formating:
    name: Formating and Linting Code Base
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install clang-format clang-tidy

      - name: Formatting Codebase
        run: clang-format -i ./src/**.* ./tests/**.* --Werror --verbose
    
      - name: Analyse Codebase
        run: clang-tidy ./src/**.*

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: (CI-Bot) Updating Documantation and Formating Codebase 
      