name: CI Meson

on:
  push:
    paths:
      - 'src/**.h'
      - 'src/**.cpp'
      - 'tests/**.*'

  pull_request:
    paths:    
      - 'src/**.h'
      - 'src/**.cpp'
      - 'tests/**.*'

  workflow_dispatch:


jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-2022, windows-2019]
        meson_version: ["1.5.0", "1.6.0",]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install meson==${{ matrix.meson_version }} ninja gcovr clang-format clang-tidy

      - name: Configure Project
        run: meson setup builddir/
        env:
          CC: gcc

      - name: Compile Debug Version
        run: meson compile -C builddir/ -v cDebug tDebug gDebug

      - name: Run Tests
        run: meson test -C builddir/ -v --suite t_time
           
      - name: Generating Coverage Report 
        run: ninja coverage-html 

      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}_MesonLogs
          path: |
            ./builddir/meson-logs/**.*
          if-no-files-found: error # optional, default is warn
          retention-days: 7 # optional
          include-hidden-files: false # optional, default is false